# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=20, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
