# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170115_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
