# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170115_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learning_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f\uff08\u5206\u949f\uff09'),
        ),
    ]
