# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('courses', '0004_video_learning_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.Teacher', verbose_name='\u8bfe\u7a0b\u8bb2\u5e08'),
        ),
    ]
