# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=200, verbose_name='\u8bfe\u524d\u9700\u77e5'),
        ),
    ]
